# Generated by Django 4.0.3 on 2024-04-07 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='discount_rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.discountrules', verbose_name='Regra de Desconto'),
        ),
    ]
